/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

/**
 *
 * @author Windows
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        masterdata = new javax.swing.JMenu();
        identitasmurid = new javax.swing.JMenuItem();
        identitasguru = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        nilaiuts = new javax.swing.JMenuItem();
        nilaiuas = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();
        luts = new javax.swing.JMenuItem();
        luas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("DATA");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setText("NILAI");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setText("SISWA");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel5.setText("SEKOLAH DEPOK");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel10.setText("D");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/raport.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(116, 116, 116)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bendera.jpg"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/satu.jpg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tiga.jpg"))); // NOI18N

        keluar.setBackground(new java.awt.Color(255, 255, 255));
        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/silang.png"))); // NOI18N
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(keluar))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(keluar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 255, 0));

        masterdata.setBackground(new java.awt.Color(0, 255, 0));
        masterdata.setText("Master Data");
        masterdata.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N

        identitasmurid.setBackground(new java.awt.Color(204, 255, 204));
        identitasmurid.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        identitasmurid.setText("Identitas_Murid");
        identitasmurid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identitasmuridActionPerformed(evt);
            }
        });
        masterdata.add(identitasmurid);

        identitasguru.setBackground(new java.awt.Color(204, 255, 204));
        identitasguru.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        identitasguru.setText("Identitas_Guru");
        identitasguru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identitasguruActionPerformed(evt);
            }
        });
        masterdata.add(identitasguru);

        jMenuBar1.add(masterdata);

        transaksi.setText("Transaksi");
        transaksi.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N

        nilaiuts.setBackground(new java.awt.Color(204, 255, 204));
        nilaiuts.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        nilaiuts.setText("Nilai_UTS");
        nilaiuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiutsActionPerformed(evt);
            }
        });
        transaksi.add(nilaiuts);

        nilaiuas.setBackground(new java.awt.Color(204, 255, 204));
        nilaiuas.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        nilaiuas.setText("Nilai_UAS");
        nilaiuas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiuasActionPerformed(evt);
            }
        });
        transaksi.add(nilaiuas);

        jMenuBar1.add(transaksi);

        laporan.setText("Laporan");
        laporan.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N

        luts.setBackground(new java.awt.Color(204, 255, 204));
        luts.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        luts.setText("Laporan_Uts");
        luts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lutsActionPerformed(evt);
            }
        });
        laporan.add(luts);

        luas.setBackground(new java.awt.Color(204, 255, 204));
        luas.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        luas.setText("Laporan_Uas");
        luas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luasActionPerformed(evt);
            }
        });
        laporan.add(luas);

        jMenuBar1.add(laporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void identitasmuridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identitasmuridActionPerformed
        // TODO add your handling code here:
        identitasmurid xx;
        xx = new  identitasmurid();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_identitasmuridActionPerformed

    private void identitasguruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identitasguruActionPerformed
        // TODO add your handling code here:
        identitasguru xx;
        xx = new  identitasguru();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_identitasguruActionPerformed

    private void nilaiutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiutsActionPerformed
        // TODO add your handling code here:
        nilaiuts xx;
        xx = new  nilaiuts();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nilaiutsActionPerformed

    private void nilaiuasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiuasActionPerformed
        // TODO add your handling code here:
        nilaiuas xx;
        xx = new  nilaiuas();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nilaiuasActionPerformed

    private void lutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lutsActionPerformed
        // TODO add your handling code here:
        nilaiuts xx;
        xx = new  nilaiuts();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lutsActionPerformed

    private void luasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luasActionPerformed
        // TODO add your handling code here:
        nilaiuas xx;
        xx = new  nilaiuas();
        xx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_luasActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem identitasguru;
    private javax.swing.JMenuItem identitasmurid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton keluar;
    private javax.swing.JMenu laporan;
    private javax.swing.JMenuItem luas;
    private javax.swing.JMenuItem luts;
    private javax.swing.JMenu masterdata;
    private javax.swing.JMenuItem nilaiuas;
    private javax.swing.JMenuItem nilaiuts;
    private javax.swing.JMenu transaksi;
    // End of variables declaration//GEN-END:variables
}
